# permissions for end users to edit polimorphpolicies.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: polimorph-operator
    app.kubernetes.io/managed-by: kustomize
  name: polimorphpolicy-editor-role
rules:
- apiGroups:
  - networking.twistedsolutions.se
  resources:
  - polimorphpolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - networking.twistedsolutions.se
  resources:
  - polimorphpolicies/status
  verbs:
  - get
