apiVersion: networking.twistedsolutions.se/v1alpha1
kind: FqdnNetworkPolicy
metadata:
  labels:
    app.kubernetes.io/name: fqdnnetworkpolicy
    app.kubernetes.io/instance: fqdnnetworkpolicy-sample
    app.kubernetes.io/part-of: fqdn-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: fqdn-operator
  name: fqdnnetworkpolicy-sample
spec:
  egress:
  - ports:
    - port: 443
      protocol: TCP
    to:
    - FQDN: api.github.com
    - FQDN: github.com
    - FQDN: nodejs.org
    - FQDN: registry.npmjs.org
  podSelector:
    matchLabels:
      app: example