apiVersion: networking.twistedsolutions.se/v1
kind: PoliMorphPolicy
metadata:
  name: polimorphpolicy-sample
spec:
  egress:
  - ports:
    - port: 443
      protocol: TCP
    to:
    # - FQDN: api.github.com
    # - FQDN: github.com
    # - FQDN: nodejs.org
    # - FQDN: registry.npmjs.org
    - endpoint: https://3sweden.zendesk.com/ips
      jsonPaths:
      - $.ips.ingress.all
  podSelector:
    matchLabels:
      app: example